#设置读取文件的目录
#read_file_address: "/home/xuelei/fileCheck/result.202309191548"
read_file_address: "c:/resource"

 #设置输出文件的目录
#write_file_address: "/home/xuelei/fileCheck/result.202309191548"
write_file_address: "c:/resource"

#设置调用tn的url
seed_api_url: "http://118.193.47.85:5143"

#设置调用pn的url
pn_url: "https://pnode.solarfs.io"