#设置读取文件的目录
#read_file_address: "../result.202309211506"
read_file_address: "c:/resource"

#设置输出文件的目录
#write_file_address: "../result.202309211506"
write_file_address: "c:/resource"

#设置调用tn的url
seed_api_url: "http://118.193.47.85:5143"

#设置调用pn的url
pn_url: "https://pnode.solarfs.io"

#设置读取文件的文件名
#小文件afid列表
small_file_name: "rfsDataAfidList.txt"

#大文件afid列表
large_file_name: "rawAfidList.txt"

#过期文件afid列表
expired_file_name: "expiredAfidList.txt"

#过期大文件afid列表
expiredlarge_file_name: "expiredRawAfidList.txt"

#缓冲通道数量
bufferChan_number: 1000

#工作线程数量
worker_number: 10